version: '3.8'

services:
  # Telegram бот (продакшн)
  bot:
    build: .
    container_name: events_bot
    # --- РЕКОМЕНДАЦИЯ: Добавлено правило перезапуска ---
    # Автоматически перезапускать контейнер, если он упал, но не при остановке вручную.
    restart: unless-stopped
    environment:
      # Обязательные переменные
      BOT_TOKEN: ${BOT_TOKEN}
      
      # База данных (внешняя)
      DATABASE_URL: ${DATABASE_URL}
      
      # Логирование
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}

      # Группа для модерации
      MODERATION_GROUP_ID: ${MODERATION_GROUP_ID}
      
      # AWS S3 Configuration
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL:-}
      
      # Дополнительные настройки
      ENVIRONMENT: production
      DEBUG: "false"
    # --- РЕКОМЕНДАЦИЯ: Добавлена проверка состояния (опционально) ---
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import asyncio; from events_bot.database import test_connection; asyncio.run(test_connection())"]
    #   interval: 1m
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s