name: Update Dependencies

on:
  schedule:
    # Запускается каждое воскресенье в 2:00 UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Update dependencies
      run: |
        uv lock --upgrade

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "chore: update dependencies"
        body: |
          This PR updates project dependencies to their latest versions.
          
          ## Changes
          - Updated dependencies in `uv.lock`
          
          ## Checklist
          - [ ] Tests pass
          - [ ] No breaking changes
          - [ ] Security vulnerabilities addressed
        branch: update-dependencies
        delete-branch: true
        labels: |
          dependencies
          automated 
